enabled: true
intents: 0
push:
  user: true
  tool: true
  ai: true
  thinking: false
md_selector: .ds-virtual-list--printable .ds-virtual-list-visible-items > div:last-child
  div[role="button"]:has(.ds-cross-fade)
commands: []
